- name: conditions in yaml
  hosts: localhost
  tasks:
    - name: checking user exists or not
      ansible.builtin.command: id expenseuser
      register: USER
      ignore_errors: yes

    - name: print user info
      ansible.builtin.debug:
        msg: "user info {{USER}}"
        
      
    - name : say hello if user exists
      ansible.builtin.debug:
        msg: "Hello, user exists!"