- name: conditions in yaml
  hosts: localhost
  tasks:
    - name: checking user exists or not
      ansible.builtin.command: id expenseuser
      
    - name : say hello if user exists
      ansible.builtin.debug:
        msg: "Hello, user exists!"