- name: conditions in yaml
  hosts: localhost
  vars:
    age: 20
  tasks:
    - name: Check age condition
      ansible.builtin.debug:
        msg: "You are eligible to vote."
      when: age >= 18

    - name: Check another age condition
      ansible.builtin.debug:
        msg: "You are not eligible to vote."
      when: age < 18