- name: conditions in yaml
  hosts: localhost
  tasks:
    - name: checking user exists or not
      ansible.builtin.command: id expenseuser
      register: user_check
      ignore_errors: yes

    # - name: create user if not exists
    #   ansible.builtin.command: useradd
        
      
    - name : say hello if user exists
      ansible.builtin.debug:
        msg: "Hello, user exists!"