- name: conditions based on variable values
  hosts: localhost
  vars:
   number: "number"
  tasks:
   - name: check even or odd
     ansible.builtin.set_fact:
        number: {{number | int}}
   - name: display even or odd message
     ansible.builtin.debug:
        msg: "The number {{ number }} is even"
     when: number % 2 == 0
       