- name: Install packages
  hosts: localhost
  become: yes
  tasks:
    - name: Install required packages
      ansible.builtin.dnf:
        name: '{{ item }}'
        state: present
      loop:
       -nginx
       -git
       -mysql
