- name: Install packages
  hosts: localhost
  become: yes
  tasks:
    - name: Install required packages
      ansible.builtin.dnf:
        name: '{{ item.name }}'
        state: '{{ item.state }}'
      loop:
        - {name: git, state: present}
        - {name: mysql, state: absent}
        - {name: nginx, state: absent}